sudo: required

language: shell

os: windows

env:
  global:
  - LCOW_API_PLATFORM_IF_OMITTED="linux"

  
before_install:
- choco install jdk8
- choco install docker-compose


before_script:
- cd "docker/dev"
- docker-compose up -d


script:
- mvn clean install -P test-business, test-consumer


notifications:
    email:
        recipients:
            - asadams89@gmail.com
        on_success: always
        on_failure: always



