sudo: required

language: java

services:
  - docker
  
environment:
  - MY_DOCKER_IP=192.168.99.100
    
before_install:
    - cd docker/dev
    - docker-compose up -d
    - ../../src

script: 
    - mvn clean install -P test-business, test-consumer


notifications:
    email:
        recipients:
            - asadams89@gmail.com
        on_success: always
        on_failure: always



