sudo: required

language: java

services:
  - docker
    
before_install:
    - cd docker/dev
    - docker-compose up -d

script: 
    - docker-compose ps


notifications:
    email:
        recipients:
            - asadams89@gmail.com
        on_success: always
        on_failure: always



