sudo: required

language: java

services:
  - docker
  
env:
  - MY_DOCKER_IP=127.0.0.1
    
before_script:
    - cd docker/dev
    - docker-compose up -d
    - docker-compose ps
    - cd ../../src

script: 
    - mvn clean install -P test-business,test-consumer
    
after_success:
    - mvn coveralls:report
    
notifications:
    email:
        recipients:
            - asadams89@gmail.com
        on_success: always
        on_failure: always



